export const DASHBOARD_ACCESS = {
  admin: [
    "dashboard",
    "courses",
    "categories",
    "users",
    "roles",
    "permissions",
    "rolePermissions",
    "messages",
    "comments",
    "instructors",
    "students",
    "chatRooms",
    "orders",
    "payment",
    "discount",
    "quizzes",
    "lessons",
    "questions",
    "studentQuizAttempts",
    "studentAnswer",
    "modules",
  ],

  instructor: [
    "dashboard",
    "courses",
    "lessons",
    "quizzes",
    "questions",
    "students",
    "comments",
    "studentQuizAttempts",
    "studentAnswer",
  ],

  student: [
    "dashboard",
    "studentQuizAttempts",
    "studentAnswer",
    "orders",
    "payment",
  ],
};
