export const MESSAGE_CODES = {
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_EMPTY: "MESSAGE_EMPTY",
  USER_MUTED: "USER_MUTED",
  USER_BLOCKED: "USER_BLOCKED",
  BLOCKED_BY_USER: "BLOCKED_BY_USER",
  MESSAGE_SEND_FAILED: "MESSAGE_SEND_FAILED",
  MESSAGE_LIST_SUCCESS: "MESSAGE_LIST_SUCCESS",
  MESSAGE_LIST_FAILED: "MESSAGE_LIST_FAILED",
};
