export const NOTIFICATION_CODES = {
  NOTIFICATION_SETTINGS_UPDATED: "NOTIFICATION_SETTINGS_UPDATED",
  NOTIFICATION_UPDATE_FAILED: "NOTIFICATION_UPDATE_FAILED",
  CONTACT_MESSAGE_RECEIVED: "CONTACT_MESSAGE_RECEIVED",
};
