export const QUIZ_ATTEMPT_CODES = {
  QUIZ_ATTEMPT_STARTED: "QUIZ_ATTEMPT_STARTED",
  QUIZ_ATTEMPT_START_FAILED: "QUIZ_ATTEMPT_START_FAILED",
  QUIZ_ATTEMPT_IN_PROGRESS_EXISTS: "QUIZ_ATTEMPT_IN_PROGRESS_EXISTS",
  QUIZ_ATTEMPT_LESSON_NOT_FOUND: "QUIZ_ATTEMPT_LESSON_NOT_FOUND",
  QUIZ_ATTEMPT_LESSON_LOCKED: "QUIZ_ATTEMPT_LESSON_LOCKED",
  QUIZ_ATTEMPT_NO_QUIZ: "QUIZ_ATTEMPT_NO_QUIZ",
  QUIZ_ATTEMPT_NOT_ENOUGH_PROGRESS: "QUIZ_ATTEMPT_NOT_ENOUGH_PROGRESS",
  QUIZ_ATTEMPT_ALREADY_PASSED: "QUIZ_ATTEMPT_ALREADY_PASSED",
  QUIZ_ATTEMPT_OUT_OF_ATTEMPTS: "QUIZ_ATTEMPT_OUT_OF_ATTEMPTS",
};
