export const SEARCH_CODES = {
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_FAILED: "SEARCH_FAILED",
  SEARCH_QUERY_INVALID: "SEARCH_QUERY_INVALID",
  SEARCH_LIMIT_INVALID: "SEARCH_LIMIT_INVALID",
  SEARCH_PAGE_INVALID: "SEARCH_PAGE_INVALID",
  SEARCH_EMPTY_RESULT: "SEARCH_EMPTY_RESULT",
  SEARCH_INTERNAL_ERROR: "SEARCH_INTERNAL_ERROR",
};
