export const USER_BLOCK_CODES = {
  BLOCK_ACTION_FORBIDDEN: "BLOCK_ACTION_FORBIDDEN",
  USER_BLOCKED: "USER_BLOCKED",
  USER_BLOCK_FAILED: "USER_BLOCK_FAILED",
  USER_UNBLOCKED: "USER_UNBLOCKED",
  USER_UNBLOCK_FAILED: "USER_UNBLOCK_FAILED",
};
