import {
  FiFileText,
  FiFolder,
  FiMessageCircle,
  FiMessageSquare,
  FiBookOpen,
  FiTag,
  FiUserCheck,
  FiTrendingUp,
  FiPlayCircle,
  FiEye,
  FiMail,
  FiShoppingCart,
  FiCreditCard,
  FiLock,
  FiHelpCircle,
  FiClipboard,
  FiShield,
  FiUsers,
  FiMicOff,
  FiEdit,
  FiBarChart,
  FiUser,
  FiUserX,
  FiBell,
  FiCheckCircle,
} from "react-icons/fi";

export const iconMap = {
  FileSearch: FiFileText,
  Folder: FiFolder,
  MessageCircle: FiMessageCircle,
  MessageSquare: FiMessageSquare,
  BookOpen: FiBookOpen,
  Tag: FiTag,
  UserCheck: FiUserCheck,
  TrendingUp: FiTrendingUp,
  PlayCircle: FiPlayCircle,
  Eye: FiEye,
  Mail: FiMail,
  ShoppingCart: FiShoppingCart,
  CreditCard: FiCreditCard,
  Lock: FiLock,
  HelpCircle: FiHelpCircle,
  ClipboardList: FiClipboard,
  Shield: FiShield,
  Users: FiUsers,
  MicOff: FiMicOff,
  Edit: FiEdit,
  BarChart: FiBarChart,
  User: FiUser,
  UserX: FiUserX,
  Bell: FiBell,
  BadgeCheck: FiCheckCircle,
};
